- name: update
  apt:
    update_cache: yes

- name: "copy env file"
  become: true
  copy:
    src: files/
    dest: /home/ubuntu/

- name: create directory
  file:
    path: /home/ubuntu/jenkins_home
    state: directory
    mode: '0777'

- name: install openjdk
  apt:
    name: openjdk-11-jdk

- name: downloading docker script
  command: curl -fsSL https://get.docker.com -o get-docker.sh

- name: running the docker script
  command: sh ./get-docker.sh

- name: starting docker srvice
  command: service docker start

- name: adding ubuntu user to the docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
